///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CardaData.PC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The PlanesPorProductor recording.
    /// </summary>
    [TestModule("56bee8fa-e9bd-4b16-bdd1-adcc1aac3066", ModuleType.Recording, 1)]
    public partial class PlanesPorProductor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CardaData.CardaDataRepository repository.
        /// </summary>
        public static global::CardaData.CardaDataRepository repo = global::CardaData.CardaDataRepository.Instance;

        static PlanesPorProductor instance = new PlanesPorProductor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public PlanesPorProductor()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static PlanesPorProductor Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("8bb4d90e-0931-42e5-a69e-df43fdd1058a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.lbl_PlanesPorProductor'", repo.ApplicationUnderTest.lbl_PlanesPorProductorInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.ApplicationUnderTest.lbl_PlanesPorProductorInfo.WaitForExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CodProductorPlanesProductor' at Center.", repo.ApplicationUnderTest.txt_CodProductorPlanesProductorInfo, new RecordItemIndex(1));
            //repo.ApplicationUnderTest.txt_CodProductorPlanesProductor.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LupaBuscarCodproductor' at Center.", repo.ApplicationUnderTest.LupaBuscarCodproductorInfo, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.LupaBuscarCodproductor.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.lbl_CodigosDeProductor'", repo.ApplicationUnderTest.lbl_CodigosDeProductorInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            //repo.ApplicationUnderTest.lbl_CodigosDeProductorInfo.WaitForExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CodProductor' at Center.", repo.ApplicationUnderTest.txt_CodProductorInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.txt_CodProductor.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2344' with focus on 'ApplicationUnderTest.txt_CodProductor'.", repo.ApplicationUnderTest.txt_CodProductorInfo, new RecordItemIndex(5));
            //repo.ApplicationUnderTest.txt_CodProductor.PressKeys("2344");
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_BuscarCodProductor' at Center.", repo.ApplicationUnderTest.Btn_BuscarCodProductorInfo, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.Btn_BuscarCodProductor.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.ResultadoBuscarNombreProductorAnswer'", repo.ApplicationUnderTest.ResultadoBuscarNombreProductorAnswerInfo, new ActionTimeout(30000), new RecordItemIndex(7));
            //repo.ApplicationUnderTest.ResultadoBuscarNombreProductorAnswerInfo.WaitForExists(30000);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Select_NombreProductor_Answer' at Center.", repo.ApplicationUnderTest.Select_NombreProductor_AnswerInfo, new RecordItemIndex(8));
            //repo.ApplicationUnderTest.Select_NombreProductor_Answer.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_AgregarRegistro' at Center.", repo.ApplicationUnderTest.Btn_AgregarRegistroInfo, new RecordItemIndex(9));
            repo.ApplicationUnderTest.Btn_AgregarRegistro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.FilaRegistrarProductor'", repo.ApplicationUnderTest.FilaRegistrarProductorInfo, new ActionTimeout(30000), new RecordItemIndex(10));
            repo.ApplicationUnderTest.FilaRegistrarProductorInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CanalProductor' at Center.", repo.ApplicationUnderTest.txt_CanalProductorInfo, new RecordItemIndex(11));
            repo.ApplicationUnderTest.txt_CanalProductor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(12));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Canal_DirectoAnswer' at Center.", repo.ApplicationUnderTest.Canal_DirectoAnswerInfo, new RecordItemIndex(13));
            repo.ApplicationUnderTest.Canal_DirectoAnswer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CodPAS' at Center.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(14));
            repo.ApplicationUnderTest.txt_CodPAS.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2344' with focus on 'ApplicationUnderTest.txt_CodPAS'.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(15));
            repo.ApplicationUnderTest.txt_CodPAS.PressKeys("2344");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_TipoVivienda' at Center.", repo.ApplicationUnderTest.txt_TipoViviendaInfo, new RecordItemIndex(16));
            repo.ApplicationUnderTest.txt_TipoVivienda.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(17));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Vivienda_Permanente' at Center.", repo.ApplicationUnderTest.Vivienda_PermanenteInfo, new RecordItemIndex(18));
            repo.ApplicationUnderTest.Vivienda_Permanente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.Copy_of_Vivienda_Permanente'", repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo, new ActionTimeout(30000), new RecordItemIndex(19));
            repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Plan' at Center.", repo.ApplicationUnderTest.txt_PlanInfo, new RecordItemIndex(20));
            repo.ApplicationUnderTest.txt_Plan.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(21));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Plan_LFCasaDptoPB1DegPiso' at Center.", repo.ApplicationUnderTest.Plan_LFCasaDptoPB1DegPisoInfo, new RecordItemIndex(22));
            repo.ApplicationUnderTest.Plan_LFCasaDptoPB1DegPiso.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Actalizar_Pas2344' at Center.", repo.ApplicationUnderTest.Btn_Actalizar_Pas2344Info, new RecordItemIndex(23));
            repo.ApplicationUnderTest.Btn_Actalizar_Pas2344.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(24));
            Delay.Duration(3000, false);
            
            // Header text
            Report.Log(ReportLevel.Info, "Section", "Header text", new RecordItemIndex(25));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_AgregarRegistro' at Center.", repo.ApplicationUnderTest.Btn_AgregarRegistroInfo, new RecordItemIndex(26));
            repo.ApplicationUnderTest.Btn_AgregarRegistro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.FilaRegistrarProductor'", repo.ApplicationUnderTest.FilaRegistrarProductorInfo, new ActionTimeout(30000), new RecordItemIndex(27));
            repo.ApplicationUnderTest.FilaRegistrarProductorInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CanalProductor' at Center.", repo.ApplicationUnderTest.txt_CanalProductorInfo, new RecordItemIndex(28));
            repo.ApplicationUnderTest.txt_CanalProductor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(29));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Canal_DirectoAnswer' at Center.", repo.ApplicationUnderTest.Canal_DirectoAnswerInfo, new RecordItemIndex(30));
            repo.ApplicationUnderTest.Canal_DirectoAnswer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CodPAS' at Center.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(31));
            repo.ApplicationUnderTest.txt_CodPAS.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2344' with focus on 'ApplicationUnderTest.txt_CodPAS'.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(32));
            repo.ApplicationUnderTest.txt_CodPAS.PressKeys("2344");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_TipoVivienda' at Center.", repo.ApplicationUnderTest.txt_TipoViviendaInfo, new RecordItemIndex(33));
            repo.ApplicationUnderTest.txt_TipoVivienda.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(34));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Vivienda_Permanente' at Center.", repo.ApplicationUnderTest.Vivienda_PermanenteInfo, new RecordItemIndex(35));
            repo.ApplicationUnderTest.Vivienda_Permanente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.Copy_of_Vivienda_Permanente'", repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo, new ActionTimeout(30000), new RecordItemIndex(36));
            repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Plan' at Center.", repo.ApplicationUnderTest.txt_PlanInfo, new RecordItemIndex(37));
            repo.ApplicationUnderTest.txt_Plan.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(38));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.LFCountry' at Center.", repo.ApplicationUnderTest.LFCountryInfo, new RecordItemIndex(39));
            repo.ApplicationUnderTest.LFCountry.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Actalizar_Pas2344' at Center.", repo.ApplicationUnderTest.Btn_Actalizar_Pas2344Info, new RecordItemIndex(40));
            repo.ApplicationUnderTest.Btn_Actalizar_Pas2344.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(41));
            Delay.Duration(3000, false);
            
            // Header text
            Report.Log(ReportLevel.Info, "Section", "Header text", new RecordItemIndex(42));
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_AgregarRegistro' at Center.", repo.ApplicationUnderTest.Btn_AgregarRegistroInfo, new RecordItemIndex(43));
            repo.ApplicationUnderTest.Btn_AgregarRegistro.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'ApplicationUnderTest.FilaRegistrarProductor'", repo.ApplicationUnderTest.FilaRegistrarProductorInfo, new ActionTimeout(30000), new RecordItemIndex(44));
            repo.ApplicationUnderTest.FilaRegistrarProductorInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CanalProductor' at Center.", repo.ApplicationUnderTest.txt_CanalProductorInfo, new RecordItemIndex(45));
            repo.ApplicationUnderTest.txt_CanalProductor.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(46));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Canal_DirectoAnswer' at Center.", repo.ApplicationUnderTest.Canal_DirectoAnswerInfo, new RecordItemIndex(47));
            repo.ApplicationUnderTest.Canal_DirectoAnswer.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_CodPAS' at Center.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(48));
            repo.ApplicationUnderTest.txt_CodPAS.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '2344' with focus on 'ApplicationUnderTest.txt_CodPAS'.", repo.ApplicationUnderTest.txt_CodPASInfo, new RecordItemIndex(49));
            repo.ApplicationUnderTest.txt_CodPAS.PressKeys("2344");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_TipoVivienda' at Center.", repo.ApplicationUnderTest.txt_TipoViviendaInfo, new RecordItemIndex(50));
            repo.ApplicationUnderTest.txt_TipoVivienda.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(51));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Vivienda_Permanente' at Center.", repo.ApplicationUnderTest.Vivienda_PermanenteInfo, new RecordItemIndex(52));
            repo.ApplicationUnderTest.Vivienda_Permanente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to not exist. Associated repository item: 'ApplicationUnderTest.Copy_of_Vivienda_Permanente'", repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo, new ActionTimeout(30000), new RecordItemIndex(53));
            repo.ApplicationUnderTest.Copy_of_Vivienda_PermanenteInfo.WaitForNotExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.txt_Plan' at Center.", repo.ApplicationUnderTest.txt_PlanInfo, new RecordItemIndex(54));
            repo.ApplicationUnderTest.txt_Plan.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 300ms.", new RecordItemIndex(55));
            Delay.Duration(300, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Plan_LFDpto2DegPisoOSuperior' at Center.", repo.ApplicationUnderTest.Plan_LFDpto2DegPisoOSuperiorInfo, new RecordItemIndex(56));
            repo.ApplicationUnderTest.Plan_LFDpto2DegPisoOSuperior.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Btn_Actalizar_Pas2344' at Center.", repo.ApplicationUnderTest.Btn_Actalizar_Pas2344Info, new RecordItemIndex(57));
            repo.ApplicationUnderTest.Btn_Actalizar_Pas2344.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(58));
            Delay.Duration(3000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
