///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CardaData.PC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SeleccionarProductores_PASS recording.
    /// </summary>
    [TestModule("50a833a6-eecc-4f93-a5a2-73349dd4bc46", ModuleType.Recording, 1)]
    public partial class SeleccionarProductores_PASS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CardaData.CardaDataRepository repository.
        /// </summary>
        public static global::CardaData.CardaDataRepository repo = global::CardaData.CardaDataRepository.Instance;

        static SeleccionarProductores_PASS instance = new SeleccionarProductores_PASS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SeleccionarProductores_PASS()
        {
            PASS = "2302";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SeleccionarProductores_PASS Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("8bb4d90e-0931-42e5-a69e-df43fdd1058a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable PASS.
        /// </summary>
        [TestVariable("82852bd0-f290-4719-afff-a73e01f9d61c")]
        public string PASS
        {
            get { return repo.PASS; }
            set { repo.PASS = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_Canal' at Center.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CanalInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_Canal.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}' with focus on 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_Canal'.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CanalInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_Canal.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocio' at Center.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocioInfo, new RecordItemIndex(2));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocio.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Back}' with focus on 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocio'.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocioInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_UnidadNegocio.PressKeys("{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente' at Center.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgenteInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{LControlKey down}{Akey}{LControlKey up}{Back}' with focus on 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente'.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgenteInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente.PressKeys("{LControlKey down}{Akey}{LControlKey up}{Back}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PASS' with focus on 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente'.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgenteInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.input_CodigoAgente.PressKeys(PASS);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.bttn_Buscar' at Center.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.bttn_BuscarInfo, new RecordItemIndex(7));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.bttn_Buscar.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.check_Pass' at Center.", repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.check_PassInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.Creacion_PlanEnlatado_Autonomia.check_Pass.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 500ms.", new RecordItemIndex(9));
            Delay.Duration(500, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
