///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CardaData.SQLDeveloper
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AbreSQLDeveloper recording.
    /// </summary>
    [TestModule("537430f0-2598-4701-85b0-be2855f5e23e", ModuleType.Recording, 1)]
    public partial class AbreSQLDeveloper : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CardaData.CardaDataRepository repository.
        /// </summary>
        public static global::CardaData.CardaDataRepository repo = global::CardaData.CardaDataRepository.Instance;

        static AbreSQLDeveloper instance = new AbreSQLDeveloper();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AbreSQLDeveloper()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AbreSQLDeveloper Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application 'C:\\Users\\maruiz\\Desktop\\sqldeveloper-19.2.1.247.2212-x64\\sqldeveloper\\sqldeveloper.exe' in normal mode.", new RecordItemIndex(0));
            Host.Local.RunApplication("C:\\Users\\maruiz\\Desktop\\sqldeveloper-19.2.1.247.2212-x64\\sqldeveloper\\sqldeveloper.exe", "", "C:\\Users\\maruiz\\Desktop\\sqldeveloper-19.2.1.247.2212-x64\\sqldeveloper", false);
            Delay.Milliseconds(1840);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OracleSQLDeveloperCUsersMaruizD.TreeItem1291441017DevDQASUPPORT' at 96;6.", repo.OracleSQLDeveloperCUsersMaruizD.TreeItem1291441017DevDQASUPPORTInfo, new RecordItemIndex(1));
            repo.OracleSQLDeveloperCUsersMaruizD.TreeItem1291441017DevDQASUPPORT.DoubleClick("96;6");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
