///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CardaData.BC
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NavegaMenuPlanesPagoBC recording.
    /// </summary>
    [TestModule("e11f2a85-9da9-4008-9ca9-db195c0f3183", ModuleType.Recording, 1)]
    public partial class NavegaMenuPlanesPagoBC : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CardaData.CardaDataRepository repository.
        /// </summary>
        public static global::CardaData.CardaDataRepository repo = global::CardaData.CardaDataRepository.Instance;

        static NavegaMenuPlanesPagoBC instance = new NavegaMenuPlanesPagoBC();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NavegaMenuPlanesPagoBC()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NavegaMenuPlanesPagoBC Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("8bb4d90e-0931-42e5-a69e-df43fdd1058a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.MenuAcciones' at 49;12.", repo.ApplicationUnderTest.MenuAccionesInfo, new RecordItemIndex(0));
            repo.ApplicationUnderTest.MenuAcciones.Click("49;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubMenuImportData' at 41;13.", repo.ApplicationUnderTest.SubMenuImportDataInfo, new RecordItemIndex(1));
            repo.ApplicationUnderTest.SubMenuImportData.Click("41;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.SubMenuAdminDataWizard' at Center.", repo.ApplicationUnderTest.SubMenuAdminDataWizardInfo, new RecordItemIndex(3));
            repo.ApplicationUnderTest.SubMenuAdminDataWizard.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Move item 'ApplicationUnderTest.SubMenuPlanDataWizard' at Center.", repo.ApplicationUnderTest.SubMenuPlanDataWizardInfo, new RecordItemIndex(4));
            repo.ApplicationUnderTest.SubMenuPlanDataWizard.MoveTo();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(5));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.SubMenuPlanDataWizard' at Center.", repo.ApplicationUnderTest.SubMenuPlanDataWizardInfo, new RecordItemIndex(6));
            repo.ApplicationUnderTest.SubMenuPlanDataWizard.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 5s to exist. Associated repository item: 'ApplicationUnderTest.lbl_UploadPlanDataExcelFile'", repo.ApplicationUnderTest.lbl_UploadPlanDataExcelFileInfo, new ActionTimeout(5000), new RecordItemIndex(7));
            repo.ApplicationUnderTest.lbl_UploadPlanDataExcelFileInfo.WaitForExists(5000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.OptionNoLoadConfiguration' at 12;8.", repo.ApplicationUnderTest.OptionNoLoadConfigurationInfo, new RecordItemIndex(8));
            repo.ApplicationUnderTest.OptionNoLoadConfiguration.Click("12;8");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
