///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CardaData.Menu
{
    public partial class MenuPpalBuscar
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidaContenidoMenu()
        {
            // TODO: Replace the following line with your code implementation.
            //throw new NotImplementedException();
            int i=0;
            
            while( i < 30){
            	
            	if(!repo.ApplicationUnderTest.SubMenu_CodigosDeProductorInfo.Exists(1000))
            	{
            		Delay.Milliseconds(1000);
            		repo.ApplicationUnderTest.Menu_Buscar.Click(Location.CenterRight);
            		
            	}else{
            	
            		break;
            	}
            	
            	i++;
            }
            
        }

    }
}
