///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace CardaData.Proveedores
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The AdminProveedores recording.
    /// </summary>
    [TestModule("e94905f8-b793-4490-9146-d54f456b3565", ModuleType.Recording, 1)]
    public partial class AdminProveedores : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::CardaData.CardaDataRepository repository.
        /// </summary>
        public static global::CardaData.CardaDataRepository repo = global::CardaData.CardaDataRepository.Instance;

        static AdminProveedores instance = new AdminProveedores();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public AdminProveedores()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static AdminProveedores Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable Ambiente.
        /// </summary>
        [TestVariable("8bb4d90e-0931-42e5-a69e-df43fdd1058a")]
        public string Ambiente
        {
            get { return repo.Ambiente; }
            set { repo.Ambiente = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Adinistracion' at Center.", repo.ApplicationUnderTest.AdinistracionInfo, new RecordItemIndex(0));
            //repo.ApplicationUnderTest.Adinistracion.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(1));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.Utilidades1' at Center.", repo.ApplicationUnderTest.Utilidades1Info, new RecordItemIndex(2));
            //repo.ApplicationUnderTest.Utilidades1.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(3));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.ImportarProveedoresDeSura' at Center.", repo.ApplicationUnderTest.ImportarProveedoresDeSuraInfo, new RecordItemIndex(4));
            //repo.ApplicationUnderTest.ImportarProveedoresDeSura.Click();
            //Delay.Milliseconds(0);
            
            //Report.Log(ReportLevel.Info, "Delay", "Waiting for 3s.", new RecordItemIndex(5));
            //Delay.Duration(3000, false);
            
            //Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.btn_ImportarProveedoresDeSura1' at Center.", repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1Info, new RecordItemIndex(6));
            //repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1.Click();
            //Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'ApplicationUnderTest.lbl_VendorImportSuraTtlBar'", repo.ApplicationUnderTest.lbl_VendorImportSuraTtlBarInfo, new ActionTimeout(120000), new RecordItemIndex(7));
            repo.ApplicationUnderTest.lbl_VendorImportSuraTtlBarInfo.WaitForExists(120000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ApplicationUnderTest.btn_ImportarProveedoresDeSura1' at Center.", repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1Info, new RecordItemIndex(8));
            repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(9));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to not exist. Associated repository item: 'ApplicationUnderTest.btn_ImportarProveedoresDeSura1_EnEspera'", repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1_EnEsperaInfo, new ActionTimeout(120000), new RecordItemIndex(10));
            repo.ApplicationUnderTest.btn_ImportarProveedoresDeSura1_EnEsperaInfo.WaitForNotExists(120000);
            
            // Acciones para el ambiente QA2 que da timeout
            Report.Log(ReportLevel.Info, "Section", "Acciones para el ambiente QA2 que da timeout", new RecordItemIndex(11));
            
            try {
                Report.Log(ReportLevel.Info, "Wait", "(Optional Action)\r\nWaiting 2m to exist. Associated repository item: 'ContinueOnFail.lbl_ErrorEnLaSolicitudDeHTTP503_COF'", repo.ContinueOnFail.lbl_ErrorEnLaSolicitudDeHTTP503_COFInfo, new ActionTimeout(120000), new RecordItemIndex(12));
                repo.ContinueOnFail.lbl_ErrorEnLaSolicitudDeHTTP503_COFInfo.WaitForExists(120000);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(12)); }
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'ContinueOnFail.bttn_Aceptar' at Center.", repo.ContinueOnFail.bttn_AceptarInfo, new RecordItemIndex(13));
                repo.ContinueOnFail.bttn_Aceptar.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(13)); }
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'F5' Press.", new RecordItemIndex(14));
            Keyboard.Press(System.Windows.Forms.Keys.F5, Keyboard.DefaultScanCode, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Mouse", "(Optional Action)\r\nMouse Left Click item 'AvisoChrome_COF.CargarDeNuevo' at Center.", repo.AvisoChrome_COF.CargarDeNuevoInfo, new RecordItemIndex(15));
                repo.AvisoChrome_COF.CargarDeNuevo.Click();
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(15)); }
            
            // ---
            Report.Log(ReportLevel.Info, "Section", "---", new RecordItemIndex(16));
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 2m to exist. Associated repository item: 'ApplicationUnderTest.ResultadoCargaProveedoresAB'", repo.ApplicationUnderTest.ResultadoCargaProveedoresABInfo, new ActionTimeout(120000), new RecordItemIndex(17));
            repo.ApplicationUnderTest.ResultadoCargaProveedoresABInfo.WaitForExists(120000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
